### ISSUE TITLE
Chatting

### ISSUE THREAD

**Issue by Emerald-chaos** [GDUcrash/GDUcrash#1]
Hello

**Comment by GDUcrash** [comment]
0 iq: normal messaging apps
1 iq: discord
𝕚𝕟𝕗𝕚𝕟𝕚𝕥𝕖 𝕚𝕢: github issues

**Comment by ok-what** [comment]
Hello!

**Comment by GDUcrash** [comment]
Why slide into my DMs when you can slide into my PRs, amiright?

**Comment by EleKtr1X** [comment]
> 0 iq: normal messaging apps
> 1 iq: discord
> 𝕚𝕟𝕗𝕚𝕟𝕚𝕥𝕖 𝕚𝕢: github issues

𝕚𝕟𝕗𝕚𝕟𝕚𝕥𝕖<sup>𝕚𝕟𝕗𝕚𝕟𝕚𝕥𝕖</sup> 𝕚𝕢: github prs that change the `README.md` file to chat

**Comment by ok-what** [comment]
Tic tac toe
|　|　 | X |
| ------ | ------ | ------ |
|　|　|　|
|‎　|　|　|

your turn

**Comment by iliasHDZ** [comment]
J
|   ⠀  | ⠀     |  **X**  |
|----|-----|-----|
| **O** | ⠀ | ⠀ |
| ⠀ | ⠀ | ⠀ |

**Comment by Chaos-emerald** [comment]
> Why slide into my DMs when you can slide into my PRs, amiright?

:meat_on_bone:  :poultry_leg:

**Comment by EleKtr1X** [comment]
> J
> |⠀|⠀|**X**|
> |-|-|-|
> |**O**|⠀|⠀|
> |⠀|⠀|

|⠀|⠀|**X**|
|-|-|-|
|**O**|**X**|⠀|
|⠀|⠀|

**Comment by Emerald-chaos** [comment]
:shipit: 🗑️

**Comment by GDUcrash** [comment]
undelete

**Comment by iliasHDZ** [comment]
ok, this is getting funny
